Replace exits with abort

diff --git a/tpm b/tpm
--- a/tpm
+++ b/tpm
@@ -125,7 +125,7 @@ insert() {
     abort "You didn't specify a password."
   fi
 
-  command mkdir -p "${_entry_path%/*}" || exit 1
+  command mkdir -p "${_entry_path%/*}" || abort "Cannot create password entry"
   printf '%s\n' "${password}" | mygpg --encrypt \
     --output "${_entry_path}"
 }
@@ -167,9 +167,9 @@ edit_entry() {
 	mygpg --output ${_tmpfile} --decrypt "${STORE_DIR}/${_entry_name}.gpg"
 
 	if [ -n "${EDITOR}" ]; then
-		${EDITOR} ${_tmpfile} || exit 1
+		${EDITOR} ${_tmpfile} || abort "Cannot open file using \$EDITOR"
 	else
-		vi ${_tmpfile} || exit 1
+		vi ${_tmpfile} || abort "Neither vi or an editor in \$EDITOR was found"
 	fi
 
 	mygpg --output "${STORE_DIR}/${_entry_name}.gpg" --encrypt ${_tmpfile}
